site_name: Jasny DB
theme: readthedocs
pages:
    - Home: index.md
    - Service Locator: service-locator.md
    - Connection: connection.md
    - Entity: entity.md
    - Entity traits:
        - Type casting: entity/type-casting.md
        - Identifiable: entity/identifiable.md
        - Change aware: entity/change-aware.md
        - Self aware: entity/self-aware.md
        - Dynamic: entity/dynamic.md
        - Enrichable: entity/enrichable.md
        - Redactable: entity/redactable.md
        - Validation: entity/validation.md
        - Lazy loading: entity/lazy-loading.md
        - Metadata: entity/metadata.md
        - Active record: entity/active-record.md
    - Entity set: entity-set.md
    - Data mapper: data-mapper.md
    - Data mapper traits:
        - Property mapping: data-mapper/property-mapping.md
        - Property casing: data-mapper/property-casting.md
        - Searching: data-mapper/searching.md
        - Sorting: data-mapper/sorting.md
        - Soft deletion: data-mapper/soft-deletion.md
    - Filter: filter.md
    - Maintainable code: maintainable-code.md 
    - Testing: testing.md
extra_css: 
    - extra.css

